"""1

Revision ID: 75a8b68adc5f
Revises: 
Create Date: 2022-01-30 15:40:21.297090

"""
import ormar
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75a8b68adc5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', ormar.fields.sqlalchemy_uuid.CHAR(36), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('items',
    sa.Column('id', ormar.fields.sqlalchemy_uuid.CHAR(36), nullable=False),
    sa.Column('title', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user', ormar.fields.sqlalchemy_uuid.CHAR(36), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_items_users_id_user'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    op.drop_table('users')
    # ### end Alembic commands ###
