"""4

Revision ID: 1252ed2647a8
Revises: a1d73ab19689
Create Date: 2022-02-20 18:05:16.408402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1252ed2647a8'
down_revision = 'a1d73ab19689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
