"""3

Revision ID: a1d73ab19689
Revises: 43e0a9877078
Create Date: 2022-02-20 14:55:39.355144

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = 'a1d73ab19689'
down_revision = '43e0a9877078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', ormar.fields.sqlalchemy_uuid.CHAR(36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('descriptions', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_table('roles_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', ormar.fields.sqlalchemy_uuid.CHAR(36), nullable=True),
    sa.Column('role', ormar.fields.sqlalchemy_uuid.CHAR(36), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['roles.id'], name='fk_roles_users_roles_role_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_roles_users_users_user_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
