"""5

Revision ID: ac1a30ee60fd
Revises: 90d47d457ec1
Create Date: 2022-02-21 21:49:46.919200

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = 'ac1a30ee60fd'
down_revision = '90d47d457ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.add_column('users', sa.Column('role', ormar.fields.sqlalchemy_uuid.CHAR(36), nullable=True))
    op.create_foreign_key('fk_users_roles_id_role', 'users', 'roles', ['role'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_roles_id_role', 'users', type_='foreignkey')
    op.drop_column('users', 'role')
    op.create_table('roles_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user', sa.CHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('role', sa.CHAR(length=36), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role'], ['roles.id'], name='fk_roles_users_roles_role_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_roles_users_users_user_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='roles_users_pkey')
    )
    # ### end Alembic commands ###
